apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sl0a069y0-nodejs
  janus-idp.io/tekton: sl0a069y0-nodejs
  backstage.io/kubernetes-id: sl0a069y0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sl0a069y0-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
